// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_gjj2aP6PlhRYs5deGTIMveCrA3LVSw',
    appId: '1:838988394311:web:53eeb8b6ae2194ae15e662',
    messagingSenderId: '838988394311',
    projectId: 'chat-d3321',
    authDomain: 'chat-d3321.firebaseapp.com',
    storageBucket: 'chat-d3321.appspot.com',
    measurementId: 'G-QN9NB72KTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BeOu7nO_rI5nj0z8X3KkHziA4xzNUIo',
    appId: '1:838988394311:android:b75f9aa1fabef9d815e662',
    messagingSenderId: '838988394311',
    projectId: 'chat-d3321',
    storageBucket: 'chat-d3321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr4iU30lfLdscYJvqGY9JtbBmFkJPrwjs',
    appId: '1:838988394311:ios:5f47b857735d2a6f15e662',
    messagingSenderId: '838988394311',
    projectId: 'chat-d3321',
    storageBucket: 'chat-d3321.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr4iU30lfLdscYJvqGY9JtbBmFkJPrwjs',
    appId: '1:838988394311:ios:d28d8541557a2bb415e662',
    messagingSenderId: '838988394311',
    projectId: 'chat-d3321',
    storageBucket: 'chat-d3321.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
